[package]
name = "TelemetryServer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde_json = "1.0.145"
socketcan = "3.5.0"
tokio = { version = "1.47.1", features = ["full"] }
